In [1]:
#import pandas
import pandas as pd
#read csv file
df = pd.read_csv(r"D:\Project\Workplace Employment Sector London Borough\sql_employment_data.csv")
df

,Year,Local_Authority_County,Code,Authority_Type,Public_FT_employees,Public_PT_employees,Public_Tot_employees,Public_Tot_employment,Private_FT_employees,Private_PT_employees,Private_Tot_employees,Private_Tot_employment,Total_FT_Employees,Total_PT_Employees,Total_Tot_employees,Total_Employment,Validation_Status,Public_Sector_Percent,Private_Sector_Percent
0,2009,City of London,E09000001,Local Authority,16102,2203,18304,18346,264922,37988,302909,313519,281023,40190,321214,331866,Invalid,5.53,94.47
1,2009,Barking and Dagenham,E09000002,Local Authority,3804,5384,9187,9199,25882,8130,34012,35031,29685,13513,43199,44230,Invalid,20.80,79.20
2,2009,Barnet,E09000003,Local Authority,16146,9841,25987,26081,58348,28639,86987,91065,74493,38481,112974,117146,Valid,22.26,77.74
3,2009,Bexley,E09000004,Local Authority,7095,5665,12760,12760,33952,17010,50962,53306,41047,22675,63722,66066,Valid,19.31,80.69
4,2009,Brent,E09000005,Local Authority,13496,4489,17985,18039,53578,21173,74751,77542,67074,25662,92735,95581,Invalid,18.87,81.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,2019,South West,E12000009,Region,237311,167197,404508,406168,1364182,728887,2093069,2229601,1601493,896084,2497577,2635769,Valid,15.41,84.59
524,2019,Wales,W92000004,Nation,185966,114504,300470,300601,640843,327305,968148,1031180,826809,441809,1268618,1331781,Valid,22.57,77.43
525,2019,Scotland,S92000003,Nation,356633,224475,581108,581151,1296720,625120,1921841,2020649,1653354,849595,2502948,2601800,Invalid,22.34,77.66
526,2019,England,E92000001,Nation,2685997,1573492,4259489,4269232,15222896,6825040,22047937,22884758,17908893,8398532,26307426,27153990,Invalid,15.72,84.28
527,2019,Great Britain,K03000001,Aggregate,3228596,1912470,5141066,5150984,17160460,7777465,24937926,25936586,20389056,9689936,30078992,31087571,Invalid,16.57,83.43

In [127]:
# display maximum rows and columns
pd.set_option('display.max_rows',532)
pd.set_option('display.max_columns',25)

In [128]:
#Structure & Data Types Overview
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 528 entries, 0 to 527
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Year                    528 non-null    int64
 1   Local_Authority_County  528 non-null    object
 2   Code                    528 non-null    object
 3   Authority_Type          528 non-null    object
 4   Public_FT_employees     528 non-null    int64
 5   Public_PT_employees     528 non-null    int64
 6   Public_Tot_employees    528 non-null    int64
 7   Public_Tot_employment   528 non-null    int64
 8   Private_FT_employees    528 non-null    int64
 9   Private_PT_employees    528 non-null    int64
 10  Private_Tot_employees   528 non-null    int64
 11  Private_Tot_employment  528 non-null    int64
 12  Total_FT_Employees      528 non-null    int64
 13  Total_PT_Employees      528 non-null    int64
 14  Total_Tot_employees     528 non-null    int64
 15  Total_Employment        528 non-null    int64
 16  Validation_Status       528 non-null    object
 17  Public_Sector_Percent   528 non-null    float64
 18  Private_Sector_Percent  528 non-null    float64
dtypes: float64(2), int64(13), object(4)
memory usage: 78.5+ KB

In [129]:
#Descriptive Statistics for Numeric Columns and excluded year 
df.describe().drop(columns = 'Year')

,Public_FT_employees,Public_PT_employees,Public_Tot_employees,Public_Tot_employment,Private_FT_employees,Private_PT_employees,Private_Tot_employees,Private_Tot_employment,Total_FT_Employees,Total_PT_Employees,Total_Tot_employees,Total_Employment,Public_Sector_Percent,Private_Sector_Percent
count,5.280000e+02,5.280000e+02,5.280000e+02,5.280000e+02,5.280000e+02,5.280000e+02,5.280000e+02,5.280000e+02,5.280000e+02,5.280000e+02,5.280000e+02,5.280000e+02,528.000000,528.000000
mean,2.220234e+05,1.293571e+05,3.513808e+05,3.600307e+05,1.039263e+06,4.530139e+05,1.488465e+06,1.548104e+06,1.285051e+06,5.910856e+05,1.876136e+06,1.946093e+06,18.438523,81.425455
std,6.178397e+05,3.752410e+05,9.923915e+05,1.019870e+06,2.894191e+06,1.284366e+06,4.175299e+06,4.345304e+06,3.564670e+06,1.681343e+06,5.244208e+06,5.442585e+06,5.101497,6.040237
min,3.804000e+03,1.940000e+03,8.092000e+03,8.104000e+03,2.558800e+04,8.130000e+03,3.401200e+04,3.503100e+04,2.968500e+04,1.351300e+04,4.319900e+04,4.423000e+04,3.070000,7.210000
25%,1.128925e+04,5.219500e+03,1.682625e+04,1.691050e+04,4.628750e+04,2.216625e+04,6.811925e+04,7.024500e+04,5.407925e+04,2.727075e+04,8.099525e+04,8.336450e+04,14.877500,77.945000
50%,1.721400e+04,7.488000e+03,2.377250e+04,2.384400e+04,8.042800e+04,3.335950e+04,1.128645e+05,1.155520e+05,9.740000e+04,3.981700e+04,1.349630e+05,1.376765e+05,18.265000,81.735000
75%,2.101558e+05,1.175935e+05,3.424298e+05,3.689890e+05,1.063744e+06,4.772928e+05,1.540374e+06,1.591346e+06,1.281686e+06,6.037418e+05,1.904036e+06,1.975260e+06,22.042500,85.122500
max,3.812835e+06,2.305929e+06,6.118764e+06,6.399383e+06,1.716046e+07,7.777465e+06,2.493793e+07,2.593659e+07,2.038906e+07,9.689936e+06,3.007899e+07,3.108757e+07,32.890000,96.930000

In [130]:
#returns null cells
df.isnull().sum()

Year                      0
Local_Authority_County    0
Code                      0
Authority_Type            0
Public_FT_employees       0
Public_PT_employees       0
Public_Tot_employees      0
Public_Tot_employment     0
Private_FT_employees      0
Private_PT_employees      0
Private_Tot_employees     0
Private_Tot_employment    0
Total_FT_Employees        0
Total_PT_Employees        0
Total_Tot_employees       0
Total_Employment          0
Validation_Status         0
Public_Sector_Percent     0
Private_Sector_Percent    0
dtype: int64

In [131]:
#remove while spaces from text columns
df["Local_Authority_County"] = df["Local_Authority_County"].str.strip()
df["Code"] = df["Code"].str.strip()
df["Authority_Type"] = df["Authority_Type"].str.strip()

In [132]:
#find missing values
df.fillna(0, inplace=True)

In [133]:
#filter rows with invalid Year
df = df[df["Year"].between(1900, 2100)]

In [134]:
#validating status
df["Validation_Status"] = df.apply(
    lambda row: "Invalid" if (
        abs(row["Public_Tot_employees"] - (row["Public_FT_employees"] + row["Public_PT_employees"])) > 0 or
        abs(row["Private_Tot_employees"] - (row["Private_FT_employees"] + row["Private_PT_employees"])) > 0 or
        abs(row["Total_Tot_employees"] - (row["Total_FT_Employees"] + row["Total_PT_Employees"])) > 0 or
        abs(row["Total_Tot_employees"] - (row["Public_Tot_employees"] + row["Private_Tot_employees"])) > 0
    ) else "Valid",
    axis=1
)

In [135]:
#count of validation status
df["Validation_Status"].value_counts()

Validation_Status
Invalid    380
Valid      148
Name: count, dtype: int64

In [136]:
#checking negative values
negatives = df[(df[numeric_cols] < 0).any(axis=1)]

In [2]:
#public vs private sector share
df["Public_sector_share"] = round(df["Public_Tot_employment"] * 100 / df["Total_Employment"], 2)
df["Private_sector_share"] = round(df["Private_Tot_employment"] * 100 / df["Total_Employment"], 2)
df

,Year,Local_Authority_County,Code,Authority_Type,Public_FT_employees,Public_PT_employees,Public_Tot_employees,Public_Tot_employment,Private_FT_employees,Private_PT_employees,...,Private_Tot_employment,Total_FT_Employees,Total_PT_Employees,Total_Tot_employees,Total_Employment,Validation_Status,Public_Sector_Percent,Private_Sector_Percent,Public_sector_share,Private_sector_share
0,2009,City of London,E09000001,Local Authority,16102,2203,18304,18346,264922,37988,...,313519,281023,40190,321214,331866,Invalid,5.53,94.47,5.53,94.47
1,2009,Barking and Dagenham,E09000002,Local Authority,3804,5384,9187,9199,25882,8130,...,35031,29685,13513,43199,44230,Invalid,20.80,79.20,20.80,79.20
2,2009,Barnet,E09000003,Local Authority,16146,9841,25987,26081,58348,28639,...,91065,74493,38481,112974,117146,Valid,22.26,77.74,22.26,77.74
3,2009,Bexley,E09000004,Local Authority,7095,5665,12760,12760,33952,17010,...,53306,41047,22675,63722,66066,Valid,19.31,80.69,19.31,80.69
4,2009,Brent,E09000005,Local Authority,13496,4489,17985,18039,53578,21173,...,77542,67074,25662,92735,95581,Invalid,18.87,81.13,18.87,81.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,2019,South West,E12000009,Region,237311,167197,404508,406168,1364182,728887,...,2229601,1601493,896084,2497577,2635769,Valid,15.41,84.59,15.41,84.59
524,2019,Wales,W92000004,Nation,185966,114504,300470,300601,640843,327305,...,1031180,826809,441809,1268618,1331781,Valid,22.57,77.43,22.57,77.43
525,2019,Scotland,S92000003,Nation,356633,224475,581108,581151,1296720,625120,...,2020649,1653354,849595,2502948,2601800,Invalid,22.34,77.66,22.34,77.66
526,2019,England,E92000001,Nation,2685997,1573492,4259489,4269232,15222896,6825040,...,22884758,17908893,8398532,26307426,27153990,Invalid,15.72,84.28,15.72,84.28
527,2019,Great Britain,K03000001,Aggregate,3228596,1912470,5141066,5150984,17160460,7777465,...,25936586,20389056,9689936,30078992,31087571,Invalid,16.57,83.43,16.57,83.43

In [138]:
# ft to pt ratio
df["ft_to_pt_ratio"] = df["Total_FT_Employees"] / df["Total_PT_Employees"].replace(0, pd.NA)

In [139]:
#authority level aggregation
authority_summary = df.groupby("Authority_Type").agg({
    "Total_Employment": ["sum", "mean", "min", "max"],
    "Public_sector_share": "mean",
    "Private_sector_share": "mean"

}).reset_index()
print(authority_summary)

    Authority_Type Total_Employment                                    \
                                sum          mean       min       max
0        Aggregate        320983782  2.918034e+07  27671593  31087571
1  Local Authority        106688754  2.771136e+05     44230   3420838
2           Nation        320983783  9.726781e+06   1254284  27153990
3           Region        278880860  2.816978e+06   1031288   5368796

  Public_sector_share Private_sector_share
                 mean                 mean
0           19.225455            74.245455
1           17.858987            82.141013
2           23.426364            76.573636
3           18.942222            81.057778

In [140]:
#top5 local authorities by employment
# Step 1: Filter for 'Local Authority' and 'Region' since nation and aggregation are totals
filtered_df = df[df["Authority_Type"].isin(["Local Authority", "Region"])]

# Step 2: Group by Local_Authority_County and sum Total_Employment
grouped = filtered_df.groupby("Local_Authority_County")["Total_Employment"].sum()

# Step 3: Get top 5 by employment
top_5_la_region = grouped.nlargest(5)
print(top_5_la_region)

Local_Authority_County
London          53349093
South East      45052011
North West      35612590
Inner London    33176453
East            29415132
Name: Total_Employment, dtype: int64

In [5]:
#year by year employment growth
df_sorted = df.sort_values(["Local_Authority_County", "Year"])
df_sorted["prev_year_employment"] = df_sorted.groupby("Local_Authority_County")["Total_Employment"].shift(1)
df_sorted["yoy_growth_percent"] = round(
    (df_sorted["Total_Employment"] - df_sorted["prev_year_employment"]) * 100 /
    df_sorted["prev_year_employment"].replace(0, pd.NA), 2
)

In [6]:
#veiw rows
pd.set_option("display.max_rows", None)
df_sorted[["Year","Local_Authority_County","Total_Employment","prev_year_employment","yoy_growth_percent"]]

,Year,Local_Authority_County,Total_Employment,prev_year_employment,yoy_growth_percent
1,2009,Barking and Dagenham,44230,NaN,NaN
49,2010,Barking and Dagenham,48337,44230.0,9.29
97,2011,Barking and Dagenham,48656,48337.0,0.66
145,2012,Barking and Dagenham,49288,48656.0,1.30
193,2013,Barking and Dagenham,49789,49288.0,1.02
241,2014,Barking and Dagenham,50701,49789.0,1.83
289,2015,Barking and Dagenham,52184,50701.0,2.92
337,2016,Barking and Dagenham,53296,52184.0,2.13
385,2017,Barking and Dagenham,56056,53296.0,5.18
433,2018,Barking and Dagenham,54824,56056.0,-2.20
481,2019,Barking and Dagenham,57644,54824.0,5.14
2,2009,Barnet,117146,NaN,NaN
50,2010,Barnet,115750,117146.0,-1.19
98,2011,Barnet,118344,115750.0,2.24
146,2012,Barnet,119881,118344.0,1.30
194,2013,Barnet,123615,119881.0,3.11
242,2014,Barnet,127568,123615.0,3.20
290,2015,Barnet,133543,127568.0,4.68
338,2016,Barnet,131921,133543.0,-1.21
386,2017,Barnet,136116,131921.0,3.18
434,2018,Barnet,134505,136116.0,-1.18
482,2019,Barnet,134254,134505.0,-0.19
3,2009,Bexley,66066,NaN,NaN
51,2010,Bexley,66700,66066.0,0.96
99,2011,Bexley,65787,66700.0,-1.37
147,2012,Bexley,67568,65787.0,2.71
195,2013,Bexley,69225,67568.0,2.45
243,2014,Bexley,69913,69225.0,0.99
291,2015,Bexley,73161,69913.0,4.65
339,2016,Bexley,74599,73161.0,1.97
387,2017,Bexley,77055,74599.0,3.29
435,2018,Bexley,75952,77055.0,-1.43
483,2019,Bexley,78110,75952.0,2.84
4,2009,Brent,95581,NaN,NaN
52,2010,Brent,99000,95581.0,3.58
100,2011,Brent,101055,99000.0,2.08
148,2012,Brent,109506,101055.0,8.36
196,2013,Brent,111267,109506.0,1.61
244,2014,Brent,114658,111267.0,3.05
292,2015,Brent,117152,114658.0,2.18
340,2016,Brent,123136,117152.0,5.11
388,2017,Brent,128232,123136.0,4.14
436,2018,Brent,126308,128232.0,-1.50
484,2019,Brent,124656,126308.0,-1.31
5,2009,Bromley,106947,NaN,NaN
53,2010,Bromley,103469,106947.0,-3.25
101,2011,Bromley,99719,103469.0,-3.62
149,2012,Bromley,101946,99719.0,2.23
197,2013,Bromley,104829,101946.0,2.83
245,2014,Bromley,106063,104829.0,1.18
293,2015,Bromley,108914,106063.0,2.69
341,2016,Bromley,108637,108914.0,-0.25
389,2017,Bromley,112577,108637.0,3.63
437,2018,Bromley,109660,112577.0,-2.59
485,2019,Bromley,109345,109660.0,-0.29
6,2009,Camden,290420,NaN,NaN
54,2010,Camden,289253,290420.0,-0.40
102,2011,Camden,310517,289253.0,7.35
150,2012,Camden,315944,310517.0,1.75
198,2013,Camden,328078,315944.0,3.84
246,2014,Camden,347879,328078.0,6.04
294,2015,Camden,353552,347879.0,1.63
342,2016,Camden,364826,353552.0,3.19
390,2017,Camden,373028,364826.0,2.25
438,2018,Camden,374790,373028.0,0.47
486,2019,Camden,382158,374790.0,1.97
0,2009,City of London,331866,NaN,NaN
48,2010,City of London,356623,331866.0,7.46
96,2011,City of London,388573,356623.0,8.96
144,2012,City of London,400777,388573.0,3.14
192,2013,City of London,391169,400777.0,-2.40
240,2014,City of London,413505,391169.0,5.71
288,2015,City of London,455505,413505.0,10.16
336,2016,City of London,488795,455505.0,7.31
384,2017,City of London,512832,488795.0,4.92
432,2018,City of London,522391,512832.0,1.86
480,2019,City of London,541817,522391.0,3.72
7,2009,Croydon,124679,NaN,NaN
55,2010,Croydon,122305,124679.0,-1.90
103,2011,Croydon,117433,122305.0,-3.98
151,2012,Croydon,115861,117433.0,-1.34
199,2013,Croydon,112905,115861.0,-2.55
247,2014,Croydon,117861,112905.0,4.39
295,2015,Croydon,119507,117861.0,1.40
343,2016,Croydon,120182,119507.0,0.56
391,2017,Croydon,127236,120182.0,5.87
439,2018,Croydon,124811,127236.0,-1.91
487,2019,Croydon,125875,124811.0,0.85
8,2009,Ealing,109546,NaN,NaN
56,2010,Ealing,112121,109546.0,2.35
104,2011,Ealing,121289,112121.0,8.18
152,2012,Ealing,123097,121289.0,1.49
200,2013,Ealing,124198,123097.0,0.89
248,2014,Ealing,132534,124198.0,6.71
296,2015,Ealing,131313,132534.0,-0.92
344,2016,Ealing,134167,131313.0,2.17
392,2017,Ealing,137755,134167.0,2.67
440,2018,Ealing,129467,137755.0,-6.02
488,2019,Ealing,137098,129467.0,5.89
40,2009,East,2540035,NaN,NaN
88,2010,East,2497050,2540035.0,-1.69
136,2011,East,2518265,2497050.0,0.85
184,2012,East,2524972,2518265.0,0.27
232,2013,East,2552679,2524972.0,1.10
280,2014,East,2659308,2552679.0,4.18
328,2015,East,2720742,2659308.0,2.31
376,2016,East,2801358,2720742.0,2.96
424,2017,East,2849826,2801358.0,1.73
472,2018,East,2880216,2849826.0,1.07
520,2019,East,2870681,2880216.0,-0.33
38,2009,East Midlands,1994786,NaN,NaN
86,2010,East Midlands,1986364,1994786.0,-0.42
134,2011,East Midlands,1982397,1986364.0,-0.20
182,2012,East Midlands,1977686,1982397.0,-0.24
230,2013,East Midlands,1982068,1977686.0,0.22
278,2014,East Midlands,2017200,1982068.0,1.77
326,2015,East Midlands,2091256,2017200.0,3.67
374,2016,East Midlands,2133285,2091256.0,2.01
422,2017,East Midlands,2155682,2133285.0,1.05
470,2018,East Midlands,2151490,2155682.0,-0.19
518,2019,East Midlands,2168159,2151490.0,0.77
9,2009,Enfield,94939,NaN,NaN
57,2010,Enfield,95763,94939.0,0.87
105,2011,Enfield,95125,95763.0,-0.67
153,2012,Enfield,100054,95125.0,5.18
201,2013,Enfield,98176,100054.0,-1.88
249,2014,Enfield,101494,98176.0,3.38
297,2015,Enfield,105460,101494.0,3.91
345,2016,Enfield,102566,105460.0,-2.74
393,2017,Enfield,108039,102566.0,5.34
441,2018,Enfield,105703,108039.0,-2.16
489,2019,Enfield,106777,105703.0,1.02
46,2009,England,24068097,NaN,NaN
94,2010,England,23981996,24068097.0,-0.36
142,2011,England,24062609,23981996.0,0.34
190,2012,England,24208241,24062609.0,0.61
238,2013,England,24481459,24208241.0,1.13
286,2014,England,25137178,24481459.0,2.68
334,2015,England,25933644,25137178.0,3.17
382,2016,England,26330381,25933644.0,1.53
430,2017,England,26681761,26330381.0,1.33
478,2018,England,26841506,26681761.0,0.60
526,2019,England,27153990,26841506.0,1.16
47,2009,Great Britain,27858190,NaN,NaN
95,2010,Great Britain,27671593,27858190.0,-0.67
143,2011,Great Britain,27796450,27671593.0,0.45
191,2012,Great Britain,27905428,27796450.0,0.39
239,2013,Great Britain,28217456,27905428.0,1.12
287,2014,Great Britain,28970019,28217456.0,2.67
335,2015,Great Britain,29819189,28970019.0,2.93
383,2016,Great Britain,30250152,29819189.0,1.45
431,2017,Great Britain,30593189,30250152.0,1.13
479,2018,Great Britain,30814545,30593189.0,0.72
527,2019,Great Britain,31087571,30814545.0,0.89
10,2009,Greenwich,69203,NaN,NaN
58,2010,Greenwich,69701,69203.0,0.72
106,2011,Greenwich,71184,69701.0,2.13
154,2012,Greenwich,71376,71184.0,0.27
202,2013,Greenwich,74503,71376.0,4.38
250,2014,Greenwich,75194,74503.0,0.93
298,2015,Greenwich,81889,75194.0,8.90
346,2016,Greenwich,80660,81889.0,-1.50
394,2017,Greenwich,87132,80660.0,8.02
442,2018,Greenwich,86405,87132.0,-0.83
490,2019,Greenwich,87022,86405.0,0.71
11,2009,Hackney,88544,NaN,NaN
59,2010,Hackney,88486,88544.0,-0.07
107,2011,Hackney,93725,88486.0,5.92
155,2012,Hackney,93882,93725.0,0.17
203,2013,Hackney,94837,93882.0,1.02
251,2014,Hackney,106150,94837.0,11.93
299,2015,Hackney,112962,106150.0,6.42
347,2016,Hackney,124861,112962.0,10.53
395,2017,Hackney,123343,124861.0,-1.22
443,2018,Hackney,128948,123343.0,4.54
491,2019,Hackney,133372,128948.0,3.43
12,2009,Hammersmith and Fulham,120538,NaN,NaN
60,2010,Hammersmith and Fulham,128039,120538.0,6.22
108,2011,Hammersmith and Fulham,125297,128039.0,-2.14
156,2012,Hammersmith and Fulham,130260,125297.0,3.96
204,2013,Hammersmith and Fulham,130267,130260.0,0.01
252,2014,Hammersmith and Fulham,130426,130267.0,0.12
300,2015,Hammersmith and Fulham,137598,130426.0,5.50
348,2016,Hammersmith and Fulham,139490,137598.0,1.38
396,2017,Hammersmith and Fulham,137579,139490.0,-1.37
444,2018,Hammersmith and Fulham,139345,137579.0,1.28
492,2019,Hammersmith and Fulham,138458,139345.0,-0.64
13,2009,Haringey,62393,NaN,NaN
61,2010,Haringey,61945,62393.0,-0.72
109,2011,Haringey,61856,61945.0,-0.14
157,2012,Haringey,63699,61856.0,2.98
205,2013,Haringey,64967,63699.0,1.99
253,2014,Haringey,70230,64967.0,8.10
301,2015,Haringey,70669,70230.0,0.63
349,2016,Haringey,68456,70669.0,-3.13
397,2017,Haringey,72579,68456.0,6.02
445,2018,Haringey,68135,72579.0,-6.12
493,2019,Haringey,68475,68135.0,0.50
14,2009,Harrow,67301,NaN,NaN
62,2010,Harrow,67737,67301.0,0.65
110,2011,Harrow,66747,67737.0,-1.46
158,2012,Harrow,68060,66747.0,1.97
206,2013,Harrow,71215,68060.0,4.64
254,2014,Harrow,74064,71215.0,4.00
302,2015,Harrow,73477,74064.0,-0.79
350,2016,Harrow,74347,73477.0,1.18
398,2017,Harrow,76496,74347.0,2.89
446,2018,Harrow,72466,76496.0,-5.27
494,2019,Harrow,72510,72466.0,0.06
15,2009,Havering,74156,NaN,NaN
63,2010,Havering,73173,74156.0,-1.33
111,2011,Havering,72659,73173.0,-0.70
159,2012,Havering,76342,72659.0,5.07
207,2013,Havering,77023,76342.0,0.89
255,2014,Havering,79298,77023.0,2.95
303,2015,Havering,81336,79298.0,2.57
351,2016,Havering,84497,81336.0,3.89
399,2017,Havering,86087,84497.0,1.88
447,2018,Havering,89379,86087.0,3.82
495,2019,Havering,86697,89379.0,-3.00
16,2009,Hillingdon,186545,NaN,NaN
64,2010,Hillingdon,184779,186545.0,-0.95
112,2011,Hillingdon,186606,184779.0,0.99
160,2012,Hillingdon,193799,186606.0,3.85
208,2013,Hillingdon,200023,193799.0,3.21
256,2014,Hillingdon,204258,200023.0,2.12
304,2015,Hillingdon,184303,204258.0,-9.77
352,2016,Hillingdon,187436,184303.0,1.70
400,2017,Hillingdon,192389,187436.0,2.64
448,2018,Hillingdon,186829,192389.0,-2.89
496,2019,Hillingdon,191115,186829.0,2.29
17,2009,Hounslow,124769,NaN,NaN
65,2010,Hounslow,127601,124769.0,2.27
113,2011,Hounslow,129116,127601.0,1.19
161,2012,Hounslow,140406,129116.0,8.74
209,2013,Hounslow,143304,140406.0,2.06
257,2014,Hounslow,140482,143304.0,-1.97
305,2015,Hounslow,163376,140482.0,16.30
353,2016,Hounslow,172841,163376.0,5.79
401,2017,Hounslow,164343,172841.0,-4.92
449,2018,Hounslow,159284,164343.0,-3.08
497,2019,Hounslow,164572,159284.0,3.32
33,2009,Inner London,2586823,NaN,NaN
81,2010,Inner London,2626587,2586823.0,1.54
129,2011,Inner London,2738115,2626587.0,4.25
177,2012,Inner London,2827655,2738115.0,3.27
225,2013,Inner London,2902505,2827655.0,2.65
273,2014,Inner London,3012045,2902505.0,3.77
321,2015,Inner London,3184810,3012045.0,5.74
369,2016,Inner London,3229662,3184810.0,1.41
417,2017,Inner London,3293441,3229662.0,1.97
465,2018,Inner London,3353972,3293441.0,1.84
513,2019,Inner London,3420838,3353972.0,1.99
18,2009,Islington,188154,NaN,NaN
66,2010,Islington,189258,188154.0,0.59
114,2011,Islington,187475,189258.0,-0.94
162,2012,Islington,193135,187475.0,3.02
210,2013,Islington,207900,193135.0,7.64
258,2014,Islington,213640,207900.0,2.76
306,2015,Islington,228624,213640.0,7.01
354,2016,Islington,232650,228624.0,1.76
402,2017,Islington,226239,232650.0,-2.76
450,2018,Islington,236273,226239.0,4.44
498,2019,Islington,239444,236273.0,1.34
19,2009,Kensington and Chelsea,113566,NaN,NaN
67,2010,Kensington and Chelsea,116744,113566.0,2.80
115,2011,Kensington and Chelsea,118475,116744.0,1.48
163,2012,Kensington and Chelsea,125294,118475.0,5.76
211,2013,Kensington and Chelsea,125102,125294.0,-0.15
259,2014,Kensington and Chelsea,125623,125102.0,0.42
307,2015,Kensington and Chelsea,132523,125623.0,5.49
355,2016,Kensington and Chelsea,130332,132523.0,-1.65
403,2017,Kensington and Chelsea,139166,130332.0,6.78
451,2018,Kensington and Chelsea,141674,139166.0,1.80
499,2019,Kensington and Chelsea,141886,141674.0,0.15
20,2009,Kingston upon Thames,77360,NaN,NaN
68,2010,Kingston upon Thames,77350,77360.0,-0.01
116,2011,Kingston upon Thames,72950,77350.0,-5.69
164,2012,Kingston upon Thames,73393,72950.0,0.61
212,2013,Kingston upon Thames,73794,73393.0,0.55
260,2014,Kingston upon Thames,72516,73794.0,-1.73
308,2015,Kingston upon Thames,83552,72516.0,15.22
356,2016,Kingston upon Thames,81919,83552.0,-1.95
404,2017,Kingston upon Thames,87057,81919.0,6.27
452,2018,Kingston upon Thames,82212,87057.0,-5.57
500,2019,Kingston upon Thames,79309,82212.0,-3.53
21,2009,Lambeth,129937,NaN,NaN
69,2010,Lambeth,126333,129937.0,-2.77
117,2011,Lambeth,130949,126333.0,3.65
165,2012,Lambeth,134216,130949.0,2.49
213,2013,Lambeth,142981,134216.0,6.53
261,2014,Lambeth,149457,142981.0,4.53
309,2015,Lambeth,162479,149457.0,8.71
357,2016,Lambeth,145251,162479.0,-10.60
405,2017,Lambeth,151973,145251.0,4.63
453,2018,Lambeth,157993,151973.0,3.96
501,2019,Lambeth,153381,157993.0,-2.92
22,2009,Lewisham,60653,NaN,NaN
70,2010,Lewisham,60761,60653.0,0.18
118,2011,Lewisham,61105,60761.0,0.57
166,2012,Lewisham,63147,61105.0,3.34
214,2013,Lewisham,65112,63147.0,3.11
262,2014,Lewisham,66157,65112.0,1.60
310,2015,Lewisham,69729,66157.0,5.40
358,2016,Lewisham,68257,69729.0,-2.11
406,2017,Lewisham,69406,68257.0,1.68
454,2018,Lewisham,67429,69406.0,-2.85
502,2019,Lewisham,67548,67429.0,0.18
41,2009,London,4272682,NaN,NaN
89,2010,London,4323562,4272682.0,1.19
137,2011,London,4449520,4323562.0,2.91
185,2012,London,4593575,4449520.0,3.24
233,2013,London,4706983,4593575.0,2.47
281,2014,London,4857311,4706983.0,3.19
329,2015,London,5080733,4857311.0,4.60
377,2016,London,5147202,5080733.0,1.31
425,2017,London,5267893,5147202.0,2.34
473,2018,London,5280836,5267893.0,0.25
521,2019,London,5368796,5280836.0,1.67
23,2009,Merton,67103,NaN,NaN
71,2010,Merton,69021,67103.0,2.86
119,2011,Merton,71487,69021.0,3.57
167,2012,Merton,75665,71487.0,5.84
215,2013,Merton,81064,75665.0,7.14
263,2014,Merton,80084,81064.0,-1.21
311,2015,Merton,80869,80084.0,0.98
359,2016,Merton,81992,80869.0,1.39
407,2017,Merton,84557,81992.0,3.13
455,2018,Merton,83450,84557.0,-1.31
503,2019,Merton,81926,83450.0,-1.83
24,2009,Newham,74730,NaN,NaN
72,2010,Newham,75061,74730.0,0.44
120,2011,Newham,77415,75061.0,3.14
168,2012,Newham,88292,77415.0,14.05
216,2013,Newham,89626,88292.0,1.51
264,2014,Newham,96492,89626.0,7.66
312,2015,Newham,101832,96492.0,5.53
360,2016,Newham,104767,101832.0,2.88
408,2017,Newham,109116,104767.0,4.15
456,2018,Newham,113302,109116.0,3.84
504,2019,Newham,113195,113302.0,-0.09
35,2009,North East,1049958,NaN,NaN
83,2010,North East,1044080,1049958.0,-0.56
131,2011,North East,1036478,1044080.0,-0.73
179,2012,North East,1031288,1036478.0,-0.50
227,2013,North East,1038926,1031288.0,0.74
275,2014,North East,1065932,1038926.0,2.60
323,2015,North East,1094425,1065932.0,2.67
371,2016,North East,1072428,1094425.0,-2.01
419,2017,North East,1096104,1072428.0,2.21
467,2018,North East,1083502,1096104.0,-1.15
515,2019,North East,1101371,1083502.0,1.65
36,2009,North West,3118252,NaN,NaN
84,2010,North West,3083238,3118252.0,-1.12
132,2011,North West,3086090,3083238.0,0.09
180,2012,North West,3104452,3086090.0,0.59
228,2013,North West,3115572,3104452.0,0.36
276,2014,North West,3183904,3115572.0,2.19
324,2015,North West,3263197,3183904.0,2.49
372,2016,North West,3343977,3263197.0,2.48
420,2017,North West,3384297,3343977.0,1.21
468,2018,North West,3431408,3384297.0,1.39
516,2019,North West,3498203,3431408.0,1.95
34,2009,Outer London,1685129,NaN,NaN
82,2010,Outer London,1696219,1685129.0,0.66
130,2011,Outer London,1710701,1696219.0,0.85
178,2012,Outer London,1765033,1710701.0,3.18
226,2013,Outer London,1803644,1765033.0,2.19
274,2014,Outer London,1844460,1803644.0,2.26
322,2015,Outer London,1895923,1844460.0,2.79
370,2016,Outer London,1917540,1895923.0,1.14
418,2017,Outer London,1974451,1917540.0,2.97
466,2018,Outer London,1926864,1974451.0,-2.41
514,2019,Outer London,1947958,1926864.0,1.09
25,2009,Redbridge,67059,NaN,NaN
73,2010,Redbridge,66246,67059.0,-1.21
121,2011,Redbridge,67874,66246.0,2.46
169,2012,Redbridge,71366,67874.0,5.14
217,2013,Redbridge,71957,71366.0,0.83
265,2014,Redbridge,76325,71957.0,6.07
313,2015,Redbridge,79226,76325.0,3.80
361,2016,Redbridge,77277,79226.0,-2.46
409,2017,Redbridge,82288,77277.0,6.48
457,2018,Redbridge,79833,82288.0,-2.98
505,2019,Redbridge,80571,79833.0,0.92
26,2009,Richmond upon Thames,71232,NaN,NaN
74,2010,Richmond upon Thames,73088,71232.0,2.61
122,2011,Richmond upon Thames,75156,73088.0,2.83
170,2012,Richmond upon Thames,74269,75156.0,-1.18
218,2013,Richmond upon Thames,77418,74269.0,4.24
266,2014,Richmond upon Thames,78463,77418.0,1.35
314,2015,Richmond upon Thames,84074,78463.0,7.15
362,2016,Richmond upon Thames,83108,84074.0,-1.15
410,2017,Richmond upon Thames,83626,83108.0,0.62
458,2018,Richmond upon Thames,81159,83626.0,-2.95
506,2019,Richmond upon Thames,83958,81159.0,3.45
45,2009,Scotland,2523054,NaN,NaN
93,2010,Scotland,2435314,2523054.0,-3.48
141,2011,Scotland,2472564,2435314.0,1.53
189,2012,Scotland,2428439,2472564.0,-1.78
237,2013,Scotland,2461055,2428439.0,1.34
285,2014,Scotland,2540169,2461055.0,3.21
333,2015,Scotland,2564009,2540169.0,0.94
381,2016,Scotland,2586270,2564009.0,0.87
429,2017,Scotland,2589365,2586270.0,0.12
477,2018,Scotland,2611695,2589365.0,0.86
525,2019,Scotland,2601800,2611695.0,-0.38
42,2009,South East,3890939,NaN,NaN
90,2010,South East,3934664,3890939.0,1.12
138,2011,South East,3920784,3934664.0,-0.35
186,2012,South East,3933020,3920784.0,0.31
234,2013,South East,3975204,3933020.0,1.07
282,2014,South East,4046690,3975204.0,1.80
330,2015,South East,4205954,4046690.0,3.94
378,2016,South East,4277983,4205954.0,1.71
426,2017,South East,4239582,4277983.0,-0.90
474,2018,South East,4285249,4239582.0,1.08
522,2019,South East,4341942,4285249.0,1.32
43,2009,South West,2468836,NaN,NaN
91,2010,South West,2423464,2468836.0,-1.84
139,2011,South West,2393986,2423464.0,-1.22
187,2012,South West,2373345,2393986.0,-0.86
235,2013,South West,2394099,2373345.0,0.87
283,2014,South West,2478219,2394099.0,3.51
331,2015,South West,2515624,2478219.0,1.51
379,2016,South West,2548747,2515624.0,1.32
427,2017,South West,2560741,2548747.0,0.47
475,2018,South West,2597062,2560741.0,1.42
523,2019,South West,2635769,2597062.0,1.49
27,2009,Southwark,177949,NaN,NaN
75,2010,Southwark,185120,177949.0,4.03
123,2011,Southwark,194142,185120.0,4.87
171,2012,Southwark,201447,194142.0,3.76
219,2013,Southwark,203358,201447.0,0.95
267,2014,Southwark,215677,203358.0,6.06
315,2015,Southwark,232193,215677.0,7.66
363,2016,Southwark,236772,232193.0,1.97
411,2017,Southwark,239952,236772.0,1.34
459,2018,Southwark,245689,239952.0,2.39
507,2019,Southwark,253800,245689.0,3.30
28,2009,Sutton,65686,NaN,NaN
76,2010,Sutton,67527,65686.0,2.80
124,2011,Sutton,69691,67527.0,3.20
172,2012,Sutton,70166,69691.0,0.68
220,2013,Sutton,69795,70166.0,-0.53
268,2014,Sutton,70496,69795.0,1.00
316,2015,Sutton,72109,70496.0,2.29
364,2016,Sutton,73522,72109.0,1.96
412,2017,Sutton,73170,73522.0,-0.48
460,2018,Sutton,70792,73170.0,-3.25
508,2019,Sutton,72209,70792.0,2.00
29,2009,Tower Hamlets,208854,NaN,NaN
77,2010,Tower Hamlets,212121,208854.0,1.56
125,2011,Tower Hamlets,237653,212121.0,12.04
173,2012,Tower Hamlets,240413,237653.0,1.16
221,2013,Tower Hamlets,254192,240413.0,5.73
269,2014,Tower Hamlets,260008,254192.0,2.29
317,2015,Tower Hamlets,280913,260008.0,8.04
365,2016,Tower Hamlets,281717,280913.0,0.29
413,2017,Tower Hamlets,295136,281717.0,4.76
461,2018,Tower Hamlets,302638,295136.0,2.54
509,2019,Tower Hamlets,309169,302638.0,2.16
44,2009,Wales,1267039,NaN,NaN
92,2010,Wales,1254284,1267039.0,-1.01
140,2011,Wales,1261277,1254284.0,0.56
188,2012,Wales,1268748,1261277.0,0.59
236,2013,Wales,1274941,1268748.0,0.49
284,2014,Wales,1292672,1274941.0,1.39
332,2015,Wales,1321537,1292672.0,2.23
380,2016,Wales,1333501,1321537.0,0.91
428,2017,Wales,1322063,1333501.0,-0.86
476,2018,Wales,1361344,1322063.0,2.97
524,2019,Wales,1331781,1361344.0,-2.17
30,2009,Waltham Forest,55580,NaN,NaN
78,2010,Waltham Forest,56553,55580.0,1.75
126,2011,Waltham Forest,59821,56553.0,5.78
174,2012,Waltham Forest,62992,59821.0,5.30
222,2013,Waltham Forest,69545,62992.0,10.40
270,2014,Waltham Forest,72489,69545.0,4.23
318,2015,Waltham Forest,70478,72489.0,-2.77
366,2016,Waltham Forest,71435,70478.0,1.36
414,2017,Waltham Forest,74242,71435.0,3.93
462,2018,Waltham Forest,73825,74242.0,-0.56
510,2019,Waltham Forest,74311,73825.0,0.66
31,2009,Wandsworth,106256,NaN,NaN
79,2010,Wandsworth,105399,106256.0,-0.81
127,2011,Wandsworth,106735,105399.0,1.27
175,2012,Wandsworth,110882,106735.0,3.89
223,2013,Wandsworth,111509,110882.0,0.57
271,2014,Wandsworth,114693,111509.0,2.86
319,2015,Wandsworth,119730,114693.0,4.39
367,2016,Wandsworth,119575,119730.0,-0.13
415,2017,Wandsworth,122458,119575.0,2.41
463,2018,Wandsworth,121111,122458.0,-1.10

In [156]:
#veiw 10 highest growth rows
df_sorted.sort_values("yoy_growth_percent", ascending=False).head(10)

,Year,Local_Authority_County,Code,Authority_Type,Public_FT_employees,Public_PT_employees,Public_Tot_employees,Public_Tot_employment,Private_FT_employees,Private_PT_employees,Private_Tot_employees,Private_Tot_employment,Total_FT_Employees,Total_PT_Employees,Total_Tot_employees,Total_Employment,Validation_Status,Public_Sector_Percent,Private_Sector_Percent,Public_sector_share,Private_sector_share,ft_to_pt_ratio,prev_year_employment,yoy_growth_percent
305,2015,Hounslow,E09000018,Local Authority,10249,3775,14024,14042,105622,41435,147057,149334,115871,45211,161082,163376,Invalid,8.59,91.41,8.59,91.41,2.562894,140482.0,16.30
308,2015,Kingston upon Thames,E09000021,Local Authority,7229,4858,12087,12112,44317,25264,69581,71440,51547,30121,81668,83552,Valid,14.50,85.50,14.50,85.50,1.711331,72516.0,15.22
168,2012,Newham,E09000025,Local Authority,17517,4706,22223,22230,40410,23558,63968,66062,57927,28264,86191,88292,Valid,25.18,74.82,25.18,74.82,2.049498,77415.0,14.05
125,2011,Tower Hamlets,E09000030,Local Authority,33739,8814,42553,42874,156074,34395,190469,194779,189813,43209,233022,237653,Valid,18.04,81.96,18.04,81.96,4.392904,212121.0,12.04
251,2014,Hackney,E09000012,Local Authority,13635,5552,19187,19191,60834,22457,83291,86959,74469,28009,102478,106150,Valid,18.08,81.92,18.08,81.92,2.658753,94837.0,11.93
347,2016,Hackney,E09000012,Local Authority,13567,5274,18841,18864,75805,26811,102616,105998,89372,32085,121457,124861,Valid,15.11,84.89,15.11,84.89,2.785476,112962.0,10.53
222,2013,Waltham Forest,E09000031,Local Authority,11598,5252,16850,17034,35030,15544,50574,52511,46628,20796,67424,69545,Valid,24.49,75.51,24.49,75.51,2.242162,62992.0,10.40
288,2015,City of London,E09000001,Local Authority,13236,2391,15627,15655,366110,57463,423572,439850,379345,59854,439199,455505,Invalid,3.44,96.56,3.44,96.56,6.337839,413505.0,10.16
49,2010,Barking and Dagenham,E09000002,Local Authority,6695,5775,12470,12494,26623,8391,35012,35843,33318,14166,47482,48337,Invalid,25.85,74.15,25.85,74.15,2.351970,44230.0,9.29
96,2011,City of London,E09000001,Local Authority,17869,2513,20381,20435,309329,44356,353685,368139,327197,46869,374066,388573,Invalid,5.26,94.74,5.26,94.74,6.981096,356623.0,8.96

In [157]:
#negative rows
df_sorted[df_sorted["yoy_growth_percent"] < 0].head(10)

,Year,Local_Authority_County,Code,Authority_Type,Public_FT_employees,Public_PT_employees,Public_Tot_employees,Public_Tot_employment,Private_FT_employees,Private_PT_employees,Private_Tot_employees,Private_Tot_employment,Total_FT_Employees,Total_PT_Employees,Total_Tot_employees,Total_Employment,Validation_Status,Public_Sector_Percent,Private_Sector_Percent,Public_sector_share,Private_sector_share,ft_to_pt_ratio,prev_year_employment,yoy_growth_percent
433,2018,Barking and Dagenham,E09000002,Local Authority,5538,3055,8594,8595,31252,14063,45316,46229,36791,17118,53909,54824,Invalid,15.68,84.32,15.68,84.32,2.149258,56056.0,-2.20
50,2010,Barnet,E09000003,Local Authority,15146,10899,26045,26063,57701,28317,86015,89687,72847,39216,112059,115750,Invalid,22.52,77.48,22.52,77.48,1.857584,117146.0,-1.19
338,2016,Barnet,E09000003,Local Authority,13901,7915,21816,21831,70943,35197,106140,110090,84844,43112,127956,131921,Valid,16.55,83.45,16.55,83.45,1.967990,133543.0,-1.21
434,2018,Barnet,E09000003,Local Authority,13672,6309,19981,20172,72463,38149,110613,114333,86136,44458,130594,134505,Invalid,15.00,85.00,15.00,85.00,1.937469,136116.0,-1.18
482,2019,Barnet,E09000003,Local Authority,12590,7269,19859,20011,74046,36906,110953,114243,86636,44175,130811,134254,Invalid,14.91,85.09,14.91,85.09,1.961200,134505.0,-0.19
99,2011,Bexley,E09000004,Local Authority,6965,5122,12087,12097,32986,18339,51325,53690,39951,23461,63412,65787,Valid,18.39,81.61,18.39,81.61,1.702869,66700.0,-1.37
435,2018,Bexley,E09000004,Local Authority,6868,4169,11037,11083,40606,22774,63380,64868,47474,26944,74418,75952,Invalid,14.59,85.41,14.59,85.41,1.761951,77055.0,-1.43
436,2018,Brent,E09000005,Local Authority,18760,5430,24190,24213,69974,29444,99418,102094,88733,34875,123608,126308,Valid,19.17,80.83,19.17,80.83,2.544315,128232.0,-1.50
484,2019,Brent,E09000005,Local Authority,15376,6004,21380,21403,72005,28887,100892,103253,87381,34891,122272,124656,Valid,17.17,82.83,17.17,82.83,2.504399,126308.0,-1.31
53,2010,Bromley,E09000006,Local Authority,12078,9483,21561,21586,50663,28154,78815,81883,62742,37637,100376,103469,Invalid,20.86,79.14,20.86,79.14,1.667030,106947.0,-3.25

In [16]:
df_sorted["yoy_growth_percent"] = df_sorted["yoy_growth_percent"].fillna("N/A")

In [17]:
df_sorted.to_csv("D:/Project/Workplace Employment Sector London Borough/python_employment_data.csv", index=False)